[tool.black]
line-length = 88
target-version = ['py310']

[tool.isort]
profile = "black"
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = true
use_parentheses = true
ensure_newlines_before_comments = true
line-length = 88

[tool.autoflake]
check_diff = true

[tool.pyright]
include = ["app"]